// app/(auth)/otp.tsx
import React, { useEffect, useState } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  ImageBackground,
  KeyboardAvoidingView,
  Platform,
  Keyboard,
  TouchableWithoutFeedback,
  SafeAreaView,
  Dimensions,
  ScrollView,
  ActivityIndicator,
  Alert
} from 'react-native';
import { useRouter, useLocalSearchParams } from 'expo-router';
import { useAuth } from '../../context/AuthContext';
import { createClient } from '@supabase/supabase-js';

// Initialize Supabase Client for the frontend
const supabaseUrl = process.env.EXPO_PUBLIC_SUPABASE_URL || '';
const supabaseAnonKey = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY || '';
const supabase = createClient(supabaseUrl, supabaseAnonKey);

const bgImage = require('./otp login image.jpeg');
const BACKEND_URL = process.env.EXPO_PUBLIC_BACKEND_URL || 'http://192.168.1.100:3000'; 

export default function OtpScreen() {
  const router = useRouter();
  const params = useLocalSearchParams();
  
  const role = (params?.role as 'doctor' | 'patient') || 'patient';
  const phone = params?.phone as string;
  const opid = params?.opid as string;

  let login: ((userData: any) => void) | undefined = undefined;
  try {
    const auth = useAuth();
    login = auth?.login as ((userData: any) => void) | undefined;
  } catch (e) {
    login = undefined;
  }

  const [otp, setOtp] = useState('');
  const [loading, setLoading] = useState(false);
  const [keyboardVisible, setKeyboardVisible] = useState(false);

  useEffect(() => {
    const show = Keyboard.addListener('keyboardDidShow', () => setKeyboardVisible(true));
    const hide = Keyboard.addListener('keyboardDidHide', () => setKeyboardVisible(false));
    return () => {
      show.remove();
      hide.remove();
    };
  }, []);

  const onVerify = async () => {
    if (otp.length < 6) {
        Alert.alert("Error", "Please enter the 6-digit OTP.");
        return;
    }

    setLoading(true);
    
    try {
        // Format phone number to ensure it has the country code for Supabase
        let formattedPhone = phone.trim();
        if (!formattedPhone.startsWith('+')) {
            formattedPhone = formattedPhone.startsWith('91') ? `+${formattedPhone}` : `+91${formattedPhone}`;
        }

        // 1. Verify the OTP with Supabase
        const { data: authData, error: authError } = await supabase.auth.verifyOtp({
            phone: formattedPhone,
            token: otp,
            type: 'sms',
        });

        if (authError) {
            throw new Error(`Invalid OTP: ${authError.message}`);
        }

        // Grab the secure session token generated by Supabase
        const sessionToken = authData.session?.access_token;

        // 2. Hit the backend to check if the user exists in our hospital database schema
        const response = await fetch(`${BACKEND_URL}/api/auth/verify`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ role, phone: formattedPhone, opid, sessionToken })
        });

        const data = await response.json();

        if (!response.ok) {
            throw new Error(data.error || "Verification failed");
        }

        // 3. Success! Route based on verified role
        const backendUser = data.user; // This is the user data returned from our Express DB check

        if (role === 'doctor') {
            if (login) {
                login({ role: 'doctor', sessionToken, ...backendUser });
            }
            router.replace('/(doctor)/dashboard');
        } else {
            if (login) {
                login({ role: 'patient', sessionToken, ...backendUser });
            }
            router.replace('/(patient)/dashboard');
        }

    } catch (e: any) {
        Alert.alert('Login Failed', e.message);
    } finally {
        setLoading(false);
    }
  };

  return (
    <ImageBackground source={bgImage} style={styles.background} resizeMode="cover">
      <KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}>
        <TouchableWithoutFeedback onPress={Keyboard.dismiss}>
          <SafeAreaView style={styles.safeArea}>
            <ScrollView contentContainerStyle={styles.scrollContent} keyboardShouldPersistTaps="handled">
              <View style={styles.formWrapper}>
                <Text style={styles.title}>OTP Verification</Text>
                <Text style={styles.subtitle} numberOfLines={3}>
                  Enter the 6-digit code sent to your mobile to continue as {role === 'doctor' ? 'Doctor' : 'Patient'}.
                </Text>

                <View style={styles.inputGroup}>
                  <TextInput
                    style={styles.otpInput}
                    placeholder="• • • • • •"
                    placeholderTextColor="#c7c7c7"
                    value={otp}
                    onChangeText={setOtp}
                    keyboardType="number-pad"
                    maxLength={6}
                    textContentType="oneTimeCode"
                  />
                </View>

                <TouchableOpacity style={styles.primaryButton} onPress={onVerify} disabled={loading}>
                  {loading ? <ActivityIndicator color="#fff" /> : <Text style={styles.primaryButtonText}>Verify</Text>}
                </TouchableOpacity>

                <TouchableOpacity style={styles.secondaryButton} onPress={() => router.back()} disabled={loading}>
                  <Text style={styles.secondaryButtonText}>Go Back</Text>
                </TouchableOpacity>
              </View>
            </ScrollView>

            {!keyboardVisible && (
              <View style={styles.footer} pointerEvents="none">
                <Text style={styles.footerText}>Copyright © PSG Hospitals 2026 | All Rights Reserved</Text>
              </View>
            )}
          </SafeAreaView>
        </TouchableWithoutFeedback>
      </KeyboardAvoidingView>
    </ImageBackground>
  );
}

const { width } = Dimensions.get('window');
const FORM_WIDTH = Math.min(680, width - 40);

const styles = StyleSheet.create({
  flex: { flex: 1 },
  background: { flex: 1, width: '100%', height: '100%' },
  safeArea: { flex: 1 },
  scrollContent: { flexGrow: 1, justifyContent: 'flex-end', paddingBottom: 40 },
  formWrapper: { alignSelf: 'center', width: FORM_WIDTH, backgroundColor: 'rgba(255,255,255,0.96)', borderRadius: 18, padding: 24, marginHorizontal: 20, marginBottom: 20, shadowColor: '#000', shadowOffset: { width: 0, height: 6 }, shadowOpacity: 0.14, shadowRadius: 16, elevation: 8 },
  title: { fontSize: 20, fontWeight: '700', color: '#2b2b2b', textAlign: 'center' },
  subtitle: { fontSize: 14, color: '#6b6b6b', textAlign: 'center', marginTop: 8, marginBottom: 16 },
  inputGroup: { alignItems: 'center', marginBottom: 18 },
  otpInput: { width: '60%', borderRadius: 10, paddingVertical: 14, paddingHorizontal: 18, fontSize: 24, letterSpacing: 10, textAlign: 'center', backgroundColor: '#fff', borderWidth: 1, borderColor: '#eee', color: '#BA1A21' },
  primaryButton: { backgroundColor: '#BA1A21', paddingVertical: 14, borderRadius: 10, alignItems: 'center', marginBottom: 10 },
  primaryButtonText: { color: '#fff', fontWeight: '700', fontSize: 16 },
  secondaryButton: { alignItems: 'center', paddingVertical: 8 },
  secondaryButtonText: { color: '#6b6b6b', fontSize: 15 },
  footer: { position: 'absolute', left: 0, right: 0, bottom: 0, paddingVertical: 12, backgroundColor: 'transparent', alignItems: 'center' },
  footerText: { color: '#333', fontSize: 12, textAlign: 'center', opacity: 0.9 },
});